/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegisterMetadata } from "./IRegisterMetadata";
export type { IRegisterMetadataInternal } from "./IRegisterMetadataInternal";
export type { RegisterMetadata } from "./RegisterMetadata";
export type { RegisterMetadataInternal } from "./RegisterMetadataInternal";
