/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICouponSnapshotManagement__factory } from "./ICouponSnapshotManagement__factory";
export { IRegister__factory } from "./IRegister__factory";
export { IRegisterRoleManagement__factory } from "./IRegisterRoleManagement__factory";
export { ISmartContractAccessManagement__factory } from "./ISmartContractAccessManagement__factory";
