/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
import type * as extensions from "./extensions";
export type { extensions };
export type { IERC1155 } from "./IERC1155";
export type { IERC1155Internal } from "./IERC1155Internal";
export type { IERC1155Receiver } from "./IERC1155Receiver";
