/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICouponSnapshotManagementInternal,
  ICouponSnapshotManagementInternalInterface,
} from "../../../../contracts/register/snapshot/ICouponSnapshotManagementInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "transactionID",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentID",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum ICouponSnapshotManagementInternal.LockStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "AssetLocked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "transactionID",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentID",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum ICouponSnapshotManagementInternal.LockStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "AssetReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "transactionID",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentID",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum ICouponSnapshotManagementInternal.LockStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "LockCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "transactionID",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentID",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "enum ICouponSnapshotManagementInternal.LockStatus",
        name: "status",
        type: "uint8",
      },
    ],
    name: "LockSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "couponDate",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "currentTimestamp",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "nextTimestamp",
        type: "uint256",
      },
    ],
    name: "SnapshotTimestampChange",
    type: "event",
  },
] as const;

export class ICouponSnapshotManagementInternal__factory {
  static readonly abi = _abi;
  static createInterface(): ICouponSnapshotManagementInternalInterface {
    return new Interface(_abi) as ICouponSnapshotManagementInternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICouponSnapshotManagementInternal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICouponSnapshotManagementInternal;
  }
}
