/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInitializable,
  IInitializableInterface,
} from "../../../contracts/initializable/IInitializable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

export class IInitializable__factory {
  static readonly abi = _abi;
  static createInterface(): IInitializableInterface {
    return new Interface(_abi) as IInitializableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IInitializable {
    return new Contract(address, _abi, runner) as unknown as IInitializable;
  }
}
