/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IInitializableInternal,
  IInitializableInternalInterface,
} from "../../../contracts/initializable/IInitializableInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint64",
        name: "version",
        type: "uint64",
      },
    ],
    name: "Initialized",
    type: "event",
  },
] as const;

export class IInitializableInternal__factory {
  static readonly abi = _abi;
  static createInterface(): IInitializableInternalInterface {
    return new Interface(_abi) as IInitializableInternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IInitializableInternal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IInitializableInternal;
  }
}
