/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISmartContractAccessManagementInternal,
  ISmartContractAccessManagementInternalInterface,
} from "../../../../contracts/register/access/ISmartContractAccessManagementInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "contractHash",
        type: "bytes32",
      },
    ],
    name: "DisableContract",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "contractHash",
        type: "bytes32",
      },
    ],
    name: "EnableContract",
    type: "event",
  },
] as const;

export class ISmartContractAccessManagementInternal__factory {
  static readonly abi = _abi;
  static createInterface(): ISmartContractAccessManagementInternalInterface {
    return new Interface(
      _abi
    ) as ISmartContractAccessManagementInternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISmartContractAccessManagementInternal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISmartContractAccessManagementInternal;
  }
}
