/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegisterRoleManagement } from "./IRegisterRoleManagement";
export type { IRegisterRoleManagementInternal } from "./IRegisterRoleManagementInternal";
export type { RegisterRoleManagement } from "./RegisterRoleManagement";
export type { RegisterRoleManagementInternal } from "./RegisterRoleManagementInternal";
