/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CouponSnapshotManagement } from "./CouponSnapshotManagement";
export type { CouponSnapshotManagementInternal } from "./CouponSnapshotManagementInternal";
export type { ICouponSnapshotManagement } from "./ICouponSnapshotManagement";
export type { ICouponSnapshotManagementInternal } from "./ICouponSnapshotManagementInternal";
