/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Coupon } from "./Coupon";
export type { CouponInternal } from "./CouponInternal";
export type { CouponSnapshotManagement } from "./CouponSnapshotManagement";
export type { CouponSnapshotManagementInternal } from "./CouponSnapshotManagementInternal";
export type { ICoupon } from "./ICoupon";
export type { ICouponInternal } from "./ICouponInternal";
export type { ICouponSnapshotManagement } from "./ICouponSnapshotManagement";
export type { ICouponSnapshotManagementInternal } from "./ICouponSnapshotManagementInternal";
export type { IRedemption } from "./IRedemption";
export type { IRedemptionInternal } from "./IRedemptionInternal";
export type { Redemption } from "./Redemption";
export type { RedemptionInternal } from "./RedemptionInternal";
