/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITradeInternal,
  ITradeInternalInterface,
} from "../../../contracts/trade/ITradeInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "seller",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "buyer",
        type: "address",
      },
      {
        indexed: true,
        internalType: "enum ITradeInternal.TradeStatus",
        name: "status",
        type: "uint8",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
    ],
    name: "NotifyTrade",
    type: "event",
  },
] as const;

export class ITradeInternal__factory {
  static readonly abi = _abi;
  static createInterface(): ITradeInternalInterface {
    return new Interface(_abi) as ITradeInternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITradeInternal {
    return new Contract(address, _abi, runner) as unknown as ITradeInternal;
  }
}
