/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IRegisterRoleManagementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "changeAdminRole"
      | "grantBndRole"
      | "grantCakRole"
      | "grantCstRole"
      | "grantPayRole"
      | "isBnD"
      | "isCAK"
      | "isCustodian"
      | "isPay"
      | "revokeBndRole"
      | "revokeCakRole"
      | "revokeCstRole"
      | "revokePayRole"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;

  encodeFunctionData(
    functionFragment: "changeAdminRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantBndRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantCakRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantCstRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantPayRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isBnD", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "isCAK", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "isCustodian",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isPay", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "revokeBndRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCakRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCstRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokePayRole",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeAdminRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantBndRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantCakRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantCstRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantPayRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isBnD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isCAK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCustodian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeBndRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCakRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCstRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokePayRole",
    data: BytesLike
  ): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [_addressForNewAdmin: AddressLike];
  export type OutputTuple = [_addressForNewAdmin: string];
  export interface OutputObject {
    _addressForNewAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRegisterRoleManagement extends BaseContract {
  connect(runner?: ContractRunner | null): IRegisterRoleManagement;
  waitForDeployment(): Promise<this>;

  interface: IRegisterRoleManagementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changeAdminRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantBndRole: TypedContractMethod<
    [bndAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  grantCakRole: TypedContractMethod<
    [cakAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  grantCstRole: TypedContractMethod<
    [cstAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  grantPayRole: TypedContractMethod<
    [cstAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  isBnD: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isCAK: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isCustodian: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isPay: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  revokeBndRole: TypedContractMethod<
    [bndAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeCakRole: TypedContractMethod<
    [cakAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeCstRole: TypedContractMethod<
    [cstAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  revokePayRole: TypedContractMethod<
    [cstAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changeAdminRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantBndRole"
  ): TypedContractMethod<[bndAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantCakRole"
  ): TypedContractMethod<[cakAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantCstRole"
  ): TypedContractMethod<[cstAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantPayRole"
  ): TypedContractMethod<[cstAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isBnD"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCAK"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCustodian"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPay"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeBndRole"
  ): TypedContractMethod<[bndAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCakRole"
  ): TypedContractMethod<[cakAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCstRole"
  ): TypedContractMethod<[cstAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokePayRole"
  ): TypedContractMethod<[cstAddress: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
  };
}
