/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ICoupon, ICouponInterface } from "../../../src/intf/ICoupon";

const _abi = [
  {
    inputs: [],
    name: "computesCouponAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "setDateAsCurrentCoupon",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nbDays",
        type: "uint256",
      },
    ],
    name: "setNbDays",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICoupon__factory {
  static readonly abi = _abi;
  static createInterface(): ICouponInterface {
    return new Interface(_abi) as ICouponInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICoupon {
    return new Contract(address, _abi, runner) as unknown as ICoupon;
  }
}
