/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC165Internal,
  IERC165InternalInterface,
} from "../../../contracts/introspection/IERC165Internal";

const _abi = [
  {
    inputs: [],
    name: "ERC165Base__InvalidInterfaceId",
    type: "error",
  },
] as const;

export class IERC165Internal__factory {
  static readonly abi = _abi;
  static createInterface(): IERC165InternalInterface {
    return new Interface(_abi) as IERC165InternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC165Internal {
    return new Contract(address, _abi, runner) as unknown as IERC165Internal;
  }
}
