/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRedemption__factory } from "./IRedemption__factory";
export { Redemption__factory } from "./Redemption__factory";
